weights: yolov5s.pt
cfg: ''
data: ./data/customDataset_militaryVehicle.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 40
batch_size: 64
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
entity: null
name: one_class_YOLOV5s
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
save_dir: runs/train/one_class_YOLOV5s2
